### ISSUE TITLE
Validators - Rewards & Penalties

### ISSUE THREAD

**Issue by alebanzas** [gnosischain/documentation#142]
Current Page:

https://docs.gnosischain.com/node/incentives

## Tasks

- [ ] Check validity of information

### Rewards

- [ ] Calculate and show the current Yield
- [ ] Embed key information: https://dune.xyz/maxaleks/Gnosis-Beacon-Chain-(Deposits)

### Penalties

- [ ] Penalties
- [ ] Link to Penalties docs (?)
- [ ] Emphasize slashing
- [ ] Emphasize inactivity leaks (including mass-inactivity leaks)
