### ISSUE TITLE
Validator Docs - Consensus Layer Overview

### ISSUE THREAD

**Issue by alebanzas** [gnosischain/documentation#146]
Edited by: @plato-gno 

## Working Doc for Validator Docs

* [Draft: Validator Docs](https://docs.google.com/document/d/1hEFHCn0tvfbf--8_4NUc83uB0V0twxsnPKJid_AiQ2g/edit?usp=sharing)
* Shared document that we will all be editing + inviting reviewers
* Recommended Validator Docs structure already populated via headers
* Includes section of Generating Validator Keys
* Includes section on Monitoring, Migration, Updating, Exit/Withdraw

## Tasks

- [ ] Architectural Diagram
- [ ] List of Clients that are supported
- [ ] What consensus layer does
- [ ] Add link to [Annotated Ethereum 2.0 Spec](https://notes.ethereum.org/@vbuterin/SkeyEI3xv)
- [ ] Add link to [Upgrading Ethereum](https://eth2book.info/)
- [ ] Add link to Gnosis Beacon Chain parameter changes (or should this be under Protocol?)

## Linked Tasks

- [x] #147 
- [x] #149 
- [ ] #150 
- [x] #151 

### "Minimal" documentation

* As much as possible, refer readers to the actual Client's documentation
* Cover only the necessary changes to run Gnosis (vs. Ethereum)
* We should not be overcommitting ourselves, and then having to update large swathes of documentation
* If possible, work with actual client teams to edit their documentation to support Gnosis (e.g. Nethermind)

### Run as System Process, then Docker

* Our documentation should cover running as System Process, instead of always relying on Docker
* Explain the reasoning why certain ports are opened, why certain flags are set
* We -are- the canonical documentation and need to be agnostic to environment - be it Docker or system process
* In the future, we may expand to Windows, MacOS guides (e.g. in the case of Nethermind, that works on Windows)

## Old Notes

**Consensus Layer**
- [ ] List of clients
- [ ] Differences
- [ ] Official documentation/site links
- [ ] Current Client distribution graph (encourage to select the least used one)

For each Consensus Layer
- [ ] Prysm
- [ ] Lighthouse
- [ ] Nimbus
- [ ] Teku
- [ ] Lodestar

For each Consensus Client
- [ ] overview
- [ ] links to official docs
- [ ] complete setup guide (rely on official docs)
- [ ] docker sample artifacts
- [ ] other relevant info / code / artifact / package

Additional repos
- [ ] gnosischain/configs - stores different network configs
