### ISSUE TITLE
Deprioritize Prysm and Nimbus in Docs for 23 Nov release

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#239]
- Nimbus and Prysm require custom builds (i.e. you can't just take the Ethereum client and run it with `--network gnosis`
- Core Devs currently working out how to provide a Nimbus or Prysm build
- For 23 Nov release, we will only focus on Teku, Lodestar or Lighthouse

## Todos

- [x] Re-order `Step 3: Run Beacon Node` to prioritize Teku, Lodestar and Lighthouse
- [x] De-prioritize Prysm and Nimbus
- [x] Indicate on Prysm and Nimbus pages that clients are not ready yet
