### ISSUE TITLE
Add docs for Checkpoint Sync, Client versions and where to download CL clients

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#259]
## Todos

- [x] Lodestar
- [x] Teku
- [x] Lighthouse
- Nimbus (KIV)

## For each page

- [ ] Checkpoint sync
    - [x] Explain role of Checkpoint sync in docs
    - [x] Provide Checkpoint sync URLs (possibility of more than 1 in the future)
    - [x] Annotate Dockerfiles
    - [x] Annotate "Run as System Process"
- [x] Client versions
    - [x] Docs are done for Client Version xx.x
- [x] Download links to CL clients
    - [x] Provide link in "Run as System Process"
