### ISSUE TITLE
xDai Bridge Documentation - 2nd Pass

### ISSUE THREAD

**Issue by dan-gnosis** [gnosischain/documentation#53]
## xDai Bridge Documentation
- Improve the xDai Bridge documentation by adding more critical information
- Improve the xDai Bridge documentation by refactoring additional legacy TokenBridge and xDai Docs into the new version of documentation

## Docs Structure
- I have created a "structure" for the documentation
- "Key Information" holds critical "at-a-glance" information (e.g. fees & daily limits)
- "How it Works" explains 

![Image](https://user-images.githubusercontent.com/98335261/183815207-18235a03-1b30-48bb-b64e-c9af86459e41.png)

## Tasks

![Image](https://user-images.githubusercontent.com/98335261/183815819-7090ee1f-d1e1-4904-9ed9-f914cd07d8da.png)
- [x] Bug Reporting: https://immunefi.com/bounty/gnosischain/
- [x] Update bug bounty (i.e. $2mn)

![Image](https://user-images.githubusercontent.com/98335261/183815963-ac341336-876e-4f30-908d-b9e047aea8a2.png)
- [x] #91
- [x] Add the contracts to the table above, linking their Etherscan and Gnosisscan/Blockscout URLs

![Image](https://user-images.githubusercontent.com/98335261/183816404-5218bb8f-933e-478c-8c57-95dc188fd5b7.png)
- [x] Verify the Ethereum addresses of the Bridge Validators
- [x] Bridge-in transaction from Ethereum to Gnosis: https://alm-xdai.herokuapp.com/100/0xa85be9c5c914980b8505c7ccec7641ead36d2b2e589fb5ff3019c9addd429691
- [x] Is this anywhere in the legacy xDai or Tokenbridge docs?
- [x] May need to do a "bridge out" transaction from Gnosis to Ethereum to get the addresses of the Ethereum validators
- [x] Might also be able to obtain this from the bridge contracts

## Stretch Goals: 

![Image](https://user-images.githubusercontent.com/98335261/183816235-ec4e8153-5519-4887-9d1e-732c1a076c5f.png)
- [ ] Look into past transactions to the bridge and see if there is a consistent gas cost (bridge in from Ethereum, bridge out from Gnosis)

## Additional Thoughts

- We will need to create a "Tutorials" section for each Bridge (e.g. "How to run a xDai Bridge Validator")
- This can come later (refactor at a later date)
